version: "3"
services:
  agent:
    image: polinux/snmpd:alpine
    command: -c /etc/snmpd/snmpd.conf
    volumes:
      - ./snmp-agent.conf:/etc/snmpd/snmpd.conf
    deploy:
      replicas: 80

  scanner:
    #depends_on:
    #  - agent
    command: 172.16.0.0/24
    build: .

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
          - subnet: "172.16.0.0/24"